Repository AY2425S1-CS2103T-F11-2/tp, pull requests merged in 2024-10, with the labels that each got.

#67 Fix Search command to improve error handling
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: type.Bug

#76 Add Attendance into schema
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/attendance/Attendance.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedAttendance.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedRole.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High

#81 Update View Command GUI
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.css
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ViewPersonCard.fxml
Labels: priority.High

#85 Change success mark and unmark message to contain people names
  src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkAttendanceCommand.java
Labels: priority.Medium

#82 Add switch profile feature
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/SwitchCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SwitchCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/profile/Profile.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#88 Fix error when input telegram contains invalid characters
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/address/logic/parser/AttendanceMarkingCommandParser.java
Labels: type.Bug, priority.High

#90 Add Favourite Label to User Profiles
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkAttendanceCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/FavouriteStatus.java
  src/main/java/seedu/address/model/person/IsFavouritePredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/TelegramContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/TelegramContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#92 Add Sort Command
  src/main/java/seedu/address/commons/core/SortOrder.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/commons/core/SortOrderTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.Medium

#94 Add enableAssertions to build.gradle
  build.gradle
Labels: type.Task

#86 Add Member Role Detection
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: priority.High

#96 Updated `generateContactInformation()` method to also correctly display "isFavourite" status in `view` page
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: priority.Medium

#100 Modify DG UML diagram and explanations
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
Labels: type.Task

#102 Update UI Component UML Diagram
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: type.Task
